version: '3.7'

services:
  ISAAC-floor-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: isaac
    expose:
      - 3306
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - floor

  ISAAC-sensor-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: isaac
    expose:
      - 3307
    ports:
      - "3307:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    networks:
      - sensor

  ISAAC-sensor-back-end:
    image: jjuless/isaac-sensor-back-end
    links:
      - "ISAAC-sensor-database:database-sensor"
    environment:
      DB_HOST: database-sensor
      DB_USER: root
      DB_PASSWORD: isaac
      DB_DATABASE: isaac
      DB_PORT: 3307
      DB_DIALECT: mysql
    ports:
      - "3001:3001"
    restart: on-failure
    depends_on:
      - ISAAC-sensor-database
    networks:
      - sensor

  ISAAC-floor-back-end:
    image: jjuless/isaac-floor-back-end
    links:
      - "ISAAC-floor-database:database-floor"
    environment:
      DB_HOST: database-floor
      DB_USER: root
      DB_PASSWORD: isaac
      DB_DATABASE: isaac
      DB_PORT: 3306
      DB_DIALECT: mysql
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - ISAAC-floor-database
    networks:
      - floor

networks:
  floor:
  sensor: