version: '3.7'

services:
  ISAAC-floor-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: isaac
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  ISAAC-sensor-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: isaac
    ports:
      - "3307:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  ISAAC-floor-back-end:
    image: jjuless/isaac-floor-back-end
    environment:
      DB_HOST: ISAAC-floor-database
      DB_USER: root
      DB_PASSWORD: isaac
      DB_DATABASE: isaac
      DB_PORT: 3306
      DB_DIALECT: mysql
    ports:
      - "3000:80"
    depends_on:
      - ISAAC-floor-database

  ISAAC-sensor-back-end:
    image: jjuless/isaac-sensor-back-end
    environment:
      DB_HOST: ISAAC-sensor-database
      DB_USER: root
      DB_PASSWORD: isaac
      DB_DATABASE: isaac
      DB_PORT: 3307
      DB_DIALECT: mysql
    ports:
      - "3001:80"
    depends_on:
      - ISAAC-sensor-database