version: '3.7'
services:
  ISAAC-floor-database:
    image: mysql
    networks:
      - ISAAC-network
    ports:
      - 3306:3306
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: isaac

  ISAAC-sensor-database:
    image: mysql
    networks:
      - ISAAC-network
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: isaac
      MYSQL_ROOT_PASSWORD: isaac

  ISAAC-sensor-log-database:
    image: mysql
    networks:
      - ISAAC-network
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: isaac
      MYSQL_ROOT_PASSWORD: isaac

  ISAAC-floor-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - ISAAC-network
    ports:
      - 8080:80
    environment:
      PMA_HOST: ISAAC-floor-database
    depends_on:
      - ISAAC-floor-database

  ISAAC-sensor-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - ISAAC-network
    ports:
      - 8081:80
    environment:
      PMA_HOST: ISAAC-sensor-database
    depends_on:
      - ISAAC-sensor-database

  ISAAC-sensor-log-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - ISAAC-network
    ports:
      - 8082:80
    environment:
      PMA_HOST: ISAAC-sensor-log-database
    depends_on:
      - ISAAC-sensor-log-database

networks:
  ISAAC-network: