version: '3.7'

services:
  ISAAC-floor-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: isaac
    ports:
      - "3306:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  ISAAC-sensor-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: isaac
    ports:
      - "3307:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  ISAAC-sensor-log-database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: isaac
    ports:
      - "3308:3306"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  ISAAC-floor-back-end:
    image: jjuless/isaac-floor-back-end
    environment:
      DB_HOST: ISAAC-floor-database
      DB_USER: root
      DB_PASSWORD: isaac
      DB_DATABASE: isaac
      DB_PORT: 3306
      DB_DIALECT: mysql
    ports:
      - "3000:3000"
    restart: on-failure

  ISAAC-sensor-back-end:
    image: jjuless/isaac-sensor-back-end
    environment:
      DB_HOST: ISAAC-sensor-database
      DB_USER: root
      DB_PASSWORD: isaac
      DB_DATABASE: isaac
      DB_PORT: 3306
      DB_DIALECT: mysql
    ports:
      - "3001:3001"
    restart: on-failure

  ISAAC-sensor-log-back-end:
    image: jjuless/isaac-sensor-log-back-end
    environment:
      DB_HOST: ISAAC-sensor-log-database
      DB_USER: root
      DB_PASSWORD: isaac
      DB_DATABASE: isaac
      DB_PORT: 3306
      DB_DIALECT: mysql
    ports:
      - "3002:3002"
    restart: on-failure

  ISAAC-mqtt-server:
    image: mtolmtomt/mqtt-client
    ports:
      - "2020:2020"